// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP-Z8Yv52RVoYfbYxWCznXmFOqrmPdTxc',
    appId: '1:723487326302:web:a3a5b9410639a611b234cf',
    messagingSenderId: '723487326302',
    projectId: 'chat-app-80519',
    authDomain: 'chat-app-80519.firebaseapp.com',
    storageBucket: 'chat-app-80519.appspot.com',
    measurementId: 'G-LLV2HXW5X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSpcUCufsE0r-qcIuBVZmMkxHlPVdmbA',
    appId: '1:723487326302:android:14cd6269bf12fc34b234cf',
    messagingSenderId: '723487326302',
    projectId: 'chat-app-80519',
    storageBucket: 'chat-app-80519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBvP__TDt6rznQfCx5Yi41vE37zshJkzc',
    appId: '1:723487326302:ios:bf849a71a54d242bb234cf',
    messagingSenderId: '723487326302',
    projectId: 'chat-app-80519',
    storageBucket: 'chat-app-80519.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBvP__TDt6rznQfCx5Yi41vE37zshJkzc',
    appId: '1:723487326302:ios:220eba0f9be0e332b234cf',
    messagingSenderId: '723487326302',
    projectId: 'chat-app-80519',
    storageBucket: 'chat-app-80519.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
